package io.fabric8.istio.internal.api.telemetry.v1alpha1;

public enum IstioMetric {
  ALL_METRICS,
  REQUEST_COUNT,
  REQUEST_DURATION,
  REQUEST_SIZE,
  RESPONSE_SIZE,
  TCP_OPENED_CONNECTIONS,
  TCP_CLOSED_CONNECTIONS,
  TCP_SENT_BYTES,
  GRPC_REQUEST_MESSAGES,
  TCP_RECEIVED_BYTES,
  GRPC_RESPONSE_MESSAGES;
}
